version: '3.8'

services:
  backend:
    build: .
    container_name: backend-container
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: gunicorn -c gunicorn.conf.py app:app
    depends_on:
      - mysql
